// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace Warden.Core.Modrinth
{
    /// <summary>Get user's notifications</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface INotifications
    {
        /// <summary>Get user's notifications</summary>
        /// <param name="idOrUsername">The ID or username of the user</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/user/{idOrUsername}/notifications")]
        Task<IApiResponse<ICollection<Notification>>> GetUserNotificationsAsync(string idOrUsername, CancellationToken cancellationToken = default);

        /// <summary>Get notification from ID</summary>
        /// <param name="id">The ID of the notification</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/notification/{id}")]
        Task<IApiResponse<Notification>> GetAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Mark notification as read</summary>
        /// <param name="id">The ID of the notification</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Patch("/notification/{id}")]
        Task<IApiResponse> ReadAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Delete notification</summary>
        /// <param name="id">The ID of the notification</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/notification/{id}")]
        Task<IApiResponse> DeleteAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Get multiple notifications</summary>
        /// <param name="ids">The IDs of the notifications</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/notifications")]
        Task<IApiResponse<ICollection<Notification>>> GetAsync([Query(TreatAsString = true)] ModrinthQueryStrings ids, CancellationToken cancellationToken = default);

        /// <summary>Mark multiple notifications as read</summary>
        /// <param name="ids">The IDs of the notifications</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Patch("/notifications")]
        Task<IApiResponse> ReadAsync([Query(TreatAsString = true)] ModrinthQueryStrings ids, CancellationToken cancellationToken = default);

        /// <summary>Delete multiple notifications</summary>
        /// <param name="ids">The IDs of the notifications</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/notifications")]
        Task<IApiResponse> DeleteAsync([Query(TreatAsString = true)] ModrinthQueryStrings ids, CancellationToken cancellationToken = default);
    }

}