// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace Warden.Core.Modrinth
{
    /// <summary>Search projects</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface IProjects
    {
        /// <summary>Search projects</summary>
        /// <param name="query">The query to search for</param>
        /// <param name="facets">
        /// Facets are an essential concept for understanding how to filter out results.
        /// 
        /// These are the most commonly used facet types:
        /// - `project_type`
        /// - `categories` (loaders are lumped in with categories in search)
        /// - `versions`
        /// - `client_side`
        /// - `server_side`
        /// - `open_source`
        /// 
        /// Several others are also available for use, though these should not be used outside very specific use cases.
        /// - `title`
        /// - `author`
        /// - `follows`
        /// - `project_id`
        /// - `license`
        /// - `downloads`
        /// - `color`
        /// - `created_timestamp` (uses Unix timestamp)
        /// - `modified_timestamp` (uses Unix timestamp)
        /// - `date_created` (uses ISO-8601 timestamp)
        /// - `date_modified` (uses ISO-8601 timestamp)
        /// 
        /// In order to then use these facets, you need a value to filter by, as well as an operation to perform on this value.
        /// The most common operation is `:` (same as `=`), though you can also use `!=`, `>=`, `>`, `<=`, and `<`.
        /// Join together the type, operation, and value, and you've got your string.
        /// ```
        /// {type} {operation} {value}
        /// ```
        /// 
        /// Examples:
        /// ```
        /// categories = adventure
        /// versions != 1.20.1
        /// downloads <= 100
        /// ```
        /// 
        /// You then join these strings together in arrays to signal `AND` and `OR` operators.
        /// 
        /// ##### OR
        /// All elements in a single array are considered to be joined by OR statements.
        /// For example, the search `[["versions:1.16.5", "versions:1.17.1"]]` translates to `Projects that support 1.16.5 OR 1.17.1`.
        /// 
        /// ##### AND
        /// Separate arrays are considered to be joined by AND statements.
        /// For example, the search `[["versions:1.16.5"], ["project_type:modpack"]]` translates to `Projects that support 1.16.5 AND are modpacks`.
        /// </param>
        /// <param name="index">The sorting method used for sorting search results</param>
        /// <param name="offset">The offset into the search. Skips this number of results</param>
        /// <param name="limit">The number of results returned by the search</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/search")]
        Task<IApiResponse<SearchResults>> SearchAsync([Query] string query, [Query] string facets = "", [Query] Index index = Index.Relevance, [Query] int offset = 0, [Query] int limit = 10, CancellationToken cancellationToken = default);

        /// <summary>Get a project</summary>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/project/{idOrSlug}")]
        Task<IApiResponse<Project>> GetAsync(string idOrSlug, CancellationToken cancellationToken = default);

        /// <summary>Modify a project</summary>
        /// <param name="body">Modified project fields</param>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/project/{idOrSlug}")]
        Task<IApiResponse> ModifyAsync(string idOrSlug, [Body] EditableProject body, CancellationToken cancellationToken = default);

        /// <summary>Delete a project</summary>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/project/{idOrSlug}")]
        Task<IApiResponse> DeleteAsync(string idOrSlug, CancellationToken cancellationToken = default);

        /// <summary>Get multiple projects</summary>
        /// <param name="ids">The IDs and/or slugs of the projects</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/projects")]
        Task<IApiResponse<ICollection<Project>>> GetAsync([Query(TreatAsString = true)] ModrinthQueryStrings ids, CancellationToken cancellationToken = default);

        /// <summary>Bulk-edit multiple projects</summary>
        /// <param name="body">Fields to edit on all projects specified</param>
        /// <param name="ids">The IDs and/or slugs of the projects</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/projects")]
        Task<IApiResponse> PatchAsync([Query] ModrinthQueryStrings ids, [Body] PatchProjectsBody? body = default, CancellationToken cancellationToken = default);

        /// <summary>Get a list of random projects</summary>
        /// <param name="count">The number of random projects to return</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/projects_random")]
        Task<IApiResponse<ICollection<Project>>> RandomAsync([Query] int count, CancellationToken cancellationToken = default);

        /// <summary>Create a project</summary>
        /// <param name="data">data parameter</param>
        /// <param name="icon">Project icon file</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Multipart]
        [Headers("Accept: application/json")]
        [Post("/project")]
        Task<IApiResponse<Project>> CreateAsync(CreatableProject? data = default, StreamPart? icon = default, CancellationToken cancellationToken = default);

        /// <summary>Change project's icon</summary>
        /// <remarks>The new icon may be up to 256KiB in size.</remarks>
        /// <param name="ext">Image extension</param>
        /// <param name="body">body parameter</param>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Patch("/project/{idOrSlug}/icon")]
        Task<IApiResponse> ChangeIconAsync(string idOrSlug, [Query] Ext ext, StreamPart body, CancellationToken cancellationToken = default);

        /// <summary>Delete project's icon</summary>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/project/{idOrSlug}/icon")]
        Task<IApiResponse> DeleteIconAsync(string idOrSlug, CancellationToken cancellationToken = default);

        /// <summary>Check project slug/ID validity</summary>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/project/{idOrSlug}/check")]
        Task<IApiResponse<ProjectIdentifier>> CheckValidityAsync(string idOrSlug, CancellationToken cancellationToken = default);

        /// <summary>Add a gallery image</summary>
        /// <remarks>Modrinth allows you to upload files of up to 5MiB to a project's gallery.</remarks>
        /// <param name="ext">Image extension</param>
        /// <param name="featured">Whether an image is featured</param>
        /// <param name="title">Title of the image</param>
        /// <param name="description">Description of the image</param>
        /// <param name="ordering">Ordering of the image</param>
        /// <param name="body">body parameter</param>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Post("/project/{idOrSlug}/gallery")]
        Task<IApiResponse> AddGalleryImageAsync(string idOrSlug, [Query] Ext2 ext, [Query] bool featured, StreamPart body, [Query] string? title = default, [Query] string? description = default, [Query] int? ordering = default, CancellationToken cancellationToken = default);

        /// <summary>Modify a gallery image</summary>
        /// <param name="url">URL link of the image to modify</param>
        /// <param name="featured">Whether the image is featured</param>
        /// <param name="title">New title of the image</param>
        /// <param name="description">New description of the image</param>
        /// <param name="ordering">New ordering of the image</param>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Patch("/project/{idOrSlug}/gallery")]
        Task<IApiResponse> ModifyGalleryImageAsync(string idOrSlug, [Query] System.Uri url, [Query] bool? featured = default, [Query] string? title = default, [Query] string? description = default, [Query] int? ordering = default, CancellationToken cancellationToken = default);

        /// <summary>Delete a gallery image</summary>
        /// <param name="url">URL link of the image to delete</param>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/project/{idOrSlug}/gallery")]
        Task<IApiResponse> DeleteGalleryImageAsync(string idOrSlug, [Query] System.Uri url, CancellationToken cancellationToken = default);

        /// <summary>Get all of a project's dependencies</summary>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/project/{idOrSlug}/dependencies")]
        Task<IApiResponse<ProjectDependencyList>> GetDependenciesAsync(string idOrSlug, CancellationToken cancellationToken = default);

        /// <summary>Follow a project</summary>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Post("/project/{idOrSlug}/follow")]
        Task<IApiResponse> FollowAsync(string idOrSlug, CancellationToken cancellationToken = default);

        /// <summary>Unfollow a project</summary>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/project/{idOrSlug}/follow")]
        Task<IApiResponse> UnfollowAsync(string idOrSlug, CancellationToken cancellationToken = default);

        /// <summary>Schedule a project</summary>
        /// <param name="body">Information about date and requested status</param>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/project/{idOrSlug}/schedule")]
        Task<IApiResponse> ScheduleAsync(string idOrSlug, [Body] Schedule? body = default, CancellationToken cancellationToken = default);
    }

}