// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace Warden.Core.Modrinth
{
    /// <summary>Get a list of categories</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface ITags
    {
        /// <summary>Get a list of categories</summary>
        /// <remarks>Gets an array of categories, their icons, and applicable project types</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/tag/category")]
        Task<IApiResponse<ICollection<CategoryTag>>> CategoriesAsync(CancellationToken cancellationToken = default);

        /// <summary>Get a list of loaders</summary>
        /// <remarks>Gets an array of loaders, their icons, and supported project types</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/tag/loader")]
        Task<IApiResponse<ICollection<LoaderTag>>> LoadersAsync(CancellationToken cancellationToken = default);

        /// <summary>Get a list of game versions</summary>
        /// <remarks>Gets an array of game versions and information about them</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/tag/game_version")]
        Task<IApiResponse<ICollection<GameVersionTag>>> VersionsAsync(CancellationToken cancellationToken = default);

        /// <summary>Get a list of licenses</summary>
        /// <remarks>Deprecated - simply use SPDX IDs.</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [System.Obsolete]
        [Headers("Accept: application/json")]
        [Get("/tag/license")]
        Task<IApiResponse<ICollection<LicenseTag>>> LicensesAsync(CancellationToken cancellationToken = default);

        /// <summary>Get the text and title of a license</summary>
        /// <param name="id">The license ID to get the text of</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/tag/license/{id}")]
        Task<IApiResponse<License>> LicenseTextAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Get a list of donation platforms</summary>
        /// <remarks>Gets an array of donation platforms and information about them</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/tag/donation_platform")]
        Task<IApiResponse<ICollection<DonationPlatformTag>>> DonationPlatformsAsync(CancellationToken cancellationToken = default);

        /// <summary>Get a list of report types</summary>
        /// <remarks>Gets an array of valid report types</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/tag/report_type")]
        Task<IApiResponse<ICollection<string>>> ReportTypesAsync(CancellationToken cancellationToken = default);

        /// <summary>Get a list of project types</summary>
        /// <remarks>Gets an array of valid project types</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/tag/project_type")]
        Task<IApiResponse<ICollection<string>>> ProjectTypesAsync(CancellationToken cancellationToken = default);

        /// <summary>Get a list of side types</summary>
        /// <remarks>Gets an array of valid side types</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/tag/side_type")]
        Task<IApiResponse<ICollection<string>>> SideTypesAsync(CancellationToken cancellationToken = default);
    }

}