// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace Warden.Core.Modrinth
{
    /// <summary>Get a project's team members</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface ITeams
    {
        /// <summary>Get a project's team members</summary>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/project/{idOrSlug}/members")]
        Task<IApiResponse<ICollection<TeamMember>>> GetProjectMembersAsync(string idOrSlug, CancellationToken cancellationToken = default);

        /// <summary>Get a team's members</summary>
        /// <param name="id">The ID of the team</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/team/{id}/members")]
        Task<IApiResponse<ICollection<TeamMember>>> GetMembersAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Add a user to a team</summary>
        /// <param name="body">User to be added (must be the ID, usernames cannot be used here)</param>
        /// <param name="id">The ID of the team</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/team/{id}/members")]
        Task<IApiResponse> AddMemberAsync(string id, [Body] UserIdentifier? body = default, CancellationToken cancellationToken = default);

        /// <summary>Get the members of multiple teams</summary>
        /// <param name="ids">The IDs of the teams</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/teams")]
        Task<IApiResponse<ICollection<ICollection<TeamMember>>>> GetAsync([Query(TreatAsString = true)] ModrinthQueryStrings ids, CancellationToken cancellationToken = default);

        /// <summary>Join a team</summary>
        /// <param name="id">The ID of the team</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Post("/team/{id}/join")]
        Task<IApiResponse> JoinAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Modify a team member's information</summary>
        /// <param name="body">Contents to be modified</param>
        /// <param name="id">The ID of the team</param>
        /// <param name="idOrUsername">The ID or username of the user</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/team/{id}/members/{idOrUsername}")]
        Task<IApiResponse> ModifyMemberAsync(string id, string idOrUsername, [Body] ModifyTeamMemberBody? body = default, CancellationToken cancellationToken = default);

        /// <summary>Remove a member from a team</summary>
        /// <param name="id">The ID of the team</param>
        /// <param name="idOrUsername">The ID or username of the user</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/team/{id}/members/{idOrUsername}")]
        Task<IApiResponse> DeleteMemberAsync(string id, string idOrUsername, CancellationToken cancellationToken = default);

        /// <summary>Transfer team's ownership to another user</summary>
        /// <param name="body">New owner's ID</param>
        /// <param name="id">The ID of the team</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/team/{id}/owner")]
        Task<IApiResponse> TransferOwnershipAsync(string id, [Body] UserIdentifier? body = default, CancellationToken cancellationToken = default);
    }

}