// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace Warden.Core.Modrinth
{
    /// <summary>Report a project, user, or version</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface IThreads
    {
        /// <summary>Report a project, user, or version</summary>
        /// <remarks>Bring a project, user, or version to the attention of the moderators by reporting it.</remarks>
        /// <param name="body">The report to be sent</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/report")]
        Task<IApiResponse<Report>> SubmitReportAsync([Body] CreatableReport? body = default, CancellationToken cancellationToken = default);

        /// <summary>Get your open reports</summary>
        /// <param name="count">count parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/report")]
        Task<IApiResponse<ICollection<Report>>> GetOpenReportsAsync([Query] int? count = default, CancellationToken cancellationToken = default);

        /// <summary>Get report from ID</summary>
        /// <param name="id">The ID of the report</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/report/{id}")]
        Task<IApiResponse<Report>> GetReportAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Modify a report</summary>
        /// <param name="body">What to modify about the report</param>
        /// <param name="id">The ID of the report</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/report/{id}")]
        Task<IApiResponse> ModifyReportAsync(string id, [Body] Body? body = default, CancellationToken cancellationToken = default);

        /// <summary>Get multiple reports</summary>
        /// <param name="ids">The IDs of the reports</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/reports")]
        Task<IApiResponse<ICollection<Report>>> GetReportsAsync([Query] string ids, CancellationToken cancellationToken = default);

        /// <summary>Get a thread</summary>
        /// <param name="id">The ID of the thread</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/thread/{id}")]
        Task<IApiResponse<Thread>> GetAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Send a text message to a thread</summary>
        /// <param name="body">The message to be sent. Note that you only need the fields applicable for the `text` type.</param>
        /// <param name="id">The ID of the thread</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/thread/{id}")]
        Task<IApiResponse<Thread>> SendMessageAsync(string id, [Body] ThreadMessageBody? body = default, CancellationToken cancellationToken = default);

        /// <summary>Get multiple threads</summary>
        /// <param name="ids">The IDs of the threads</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/threads")]
        Task<IApiResponse<ICollection<Thread>>> GetAsync([Query(TreatAsString = true)] ModrinthQueryStrings ids, CancellationToken cancellationToken = default);

        /// <summary>Delete a thread message</summary>
        /// <param name="id">The ID of the message</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/message/{id}")]
        Task<IApiResponse> DeleteMessageAsync(string id, CancellationToken cancellationToken = default);
    }

}