// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace Warden.Core.Modrinth
{
    /// <summary>List project's versions</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface IVersions
    {
        /// <summary>List project's versions</summary>
        /// <param name="loaders">The types of loaders to filter for</param>
        /// <param name="game_versions">The game versions to filter for</param>
        /// <param name="featured">Allows to filter for featured or non-featured versions only</param>
        /// <param name="include_changelog">Allows you to toggle the inclusion of the changelog field in the response. It is highly recommended to use include_changelog=false in most cases unless you specifically need the changelog for all versions.</param>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/project/{idOrSlug}/version")]
        Task<IApiResponse<ICollection<Version>>> GetProjectVersionsAsync(string idOrSlug, [Query(TreatAsString = true)] ModrinthQueryStrings? loaders = default, [Query] string? game_versions = default, [Query] bool? featured = default, [Query] bool? include_changelog = true, CancellationToken cancellationToken = default);

        /// <summary>Get a version</summary>
        /// <param name="id">The ID of the version</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/version/{id}")]
        Task<IApiResponse<Version>> GetAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Modify a version</summary>
        /// <param name="body">Modified version fields</param>
        /// <param name="id">The ID of the version</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Patch("/version/{id}")]
        Task<IApiResponse> ModifyAsync(string id, [Body] EditableVersion? body = default, CancellationToken cancellationToken = default);

        /// <summary>Delete a version</summary>
        /// <param name="id">The ID of the version</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/version/{id}")]
        Task<IApiResponse> DeleteAsync(string id, CancellationToken cancellationToken = default);

        /// <summary>Get a version given a version number or ID</summary>
        /// <remarks>Please note that, if the version number provided matches multiple versions, only the **oldest matching version** will be returned.</remarks>
        /// <param name="idOrSlug">The ID or slug of the project</param>
        /// <param name="idOrNumber">The version ID or version number</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/project/{idOrSlug}/version/{idOrNumber}")]
        Task<IApiResponse<Version>> GetFromIdOrNumberAsync(string idOrSlug, string idOrNumber, CancellationToken cancellationToken = default);

        /// <summary>Create a version</summary>
        /// <remarks>
        /// This route creates a version on an existing project. There must be at least one file attached to each new version, unless the new version's status is `draft`. `.mrpack`, `.jar`, `.zip`, and `.litemod` files are accepted.
        /// 
        /// The request is a [multipart request](https://www.ietf.org/rfc/rfc2388.txt) with at least two form fields: one is `data`, which includes a JSON body with the version metadata as shown below, and at least one field containing an upload file.
        /// 
        /// You can name the file parts anything you would like, but you must list each of the parts' names in `file_parts`, and optionally, provide one to use as the primary file in `primary_file`.
        /// </remarks>
        /// <param name="data">data parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Multipart]
        [Headers("Accept: application/json")]
        [Post("/version")]
        Task<IApiResponse<Version>> CreateAsync(CreatableVersion? data = default, CancellationToken cancellationToken = default);

        /// <summary>Schedule a version</summary>
        /// <param name="body">Information about date and requested status</param>
        /// <param name="id">The ID of the version</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/version/{id}/schedule")]
        Task<IApiResponse> ScheduleAsync(string id, [Body] Schedule? body = default, CancellationToken cancellationToken = default);

        /// <summary>Get multiple versions</summary>
        /// <param name="ids">The IDs of the versions</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/versions")]
        Task<IApiResponse<ICollection<Version>>> GetAsync([Query(TreatAsString = true)] ModrinthQueryStrings ids, CancellationToken cancellationToken = default);

        /// <summary>Add files to version</summary>
        /// <remarks>Project files are attached. `.mrpack` and `.jar` files are accepted.</remarks>
        /// <param name="id">The ID of the version</param>
        /// <param name="data">data parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Multipart]
        [Headers("Accept: application/json")]
        [Post("/version/{id}/file")]
        Task<IApiResponse> AddFilesAsync(string id, Data? data = default, CancellationToken cancellationToken = default);
    }

}