// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

#nullable enable annotations

namespace Warden.Core.Modrinth
{
    /// <summary>Get version from hash</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface IVersionFiles
    {
        /// <summary>Get version from hash</summary>
        /// <param name="multiple">Whether to return multiple results when looking for this hash</param>
        /// <param name="hash">The hash of the file, considering its byte content, and encoded in hexadecimal</param>
        /// <param name="algorithm">The algorithm of the hash</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Get("/version_file/{hash}")]
        Task<IApiResponse<Version>> FromHashAsync(string hash, [Query] Algorithm algorithm, [Query] bool? multiple = false, CancellationToken cancellationToken = default);

        /// <summary>Delete a file from its hash</summary>
        /// <param name="version_id">Version ID to delete the version from, if multiple files of the same hash exist</param>
        /// <param name="hash">The hash of the file, considering its byte content, and encoded in hexadecimal</param>
        /// <param name="algorithm">The algorithm of the hash</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Incorrect token scopes or no authorization to access the requested item(s)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json")]
        [Delete("/version_file/{hash}")]
        Task<IApiResponse> DeleteFileFromHashAsync(string hash, [Query] Algorithm algorithm, [Query] string? version_id = default, CancellationToken cancellationToken = default);

        /// <summary>Latest version of a project from a hash, loader(s), and game version(s)</summary>
        /// <param name="body">Parameters of the updated version requested</param>
        /// <param name="hash">The hash of the file, considering its byte content, and encoded in hexadecimal</param>
        /// <param name="algorithm">The algorithm of the hash</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Expected response to a valid request</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The requested item(s) were not found or no authorization to access the requested item(s)</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/version_file/{hash}/update")]
        Task<IApiResponse<Version>> GetLatestFromHashAsync(string hash, [Query] Algorithm algorithm, [Body] GetLatestVersionFromHashBody? body = default, CancellationToken cancellationToken = default);

        /// <summary>Get versions from hashes</summary>
        /// <remarks>This is the same as [`/version_file/{hash}`](#operation/versionFromHash) except it accepts multiple hashes.</remarks>
        /// <param name="body">Hashes and algorithm of the versions requested</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>Expected response to a valid request</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/version_files")]
        Task<IApiResponse<IDictionary<string, Version>>> FromHashesAsync([Body] HashList? body = default, CancellationToken cancellationToken = default);

        /// <summary>Latest versions of multiple project from hashes, loader(s), and game version(s)</summary>
        /// <remarks>This is the same as [`/version_file/{hash}/update`](#operation/getLatestVersionFromHash) except it accepts multiple hashes.</remarks>
        /// <param name="body">Parameters of the updated version requested</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>Expected response to a valid request</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Request was invalid, see given error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/version_files/update")]
        Task<IApiResponse<IDictionary<string, Version>>> GetLatestFromHashesAsync([Body] GetLatestVersionsFromHashesBody? body = default, CancellationToken cancellationToken = default);
    }

}